---
abstract: 'automatically add an ACKNOWLEDGMENTS section to pod'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200013, CPAN::Meta::Converter version 2.112150'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-Section-Acknowledgements
no_index:
  file:
    - perlcritic.rc
requires:
  Moose: 0
  Moose::Autobox: 0
  Pod::Elemental::Element::Nested: 0
  Pod::Elemental::Element::Pod5::Verbatim: 0
  Pod::Weaver::Role::Section: 0
  namespace::autoclean: 0
  perl: 5.008
resources:
  bugtracker: https://github.com/xenoterracide/Pod-Weaver-Section-Acknowledgements/issues
  repository: git://github.com/xenoterracide/Pod-Weaver-Section-Acknowledgements.git
version: 0.1.0
